"""Initial migration

Revision ID: 459ea10c704c
Revises: 
Create Date: 2025-08-11 19:55:35.545967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '459ea10c704c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('send_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_messages_id'), 'scheduled_messages', ['id'], unique=False)
    op.create_index(op.f('ix_scheduled_messages_is_sent'), 'scheduled_messages', ['is_sent'], unique=False)
    op.create_index(op.f('ix_scheduled_messages_phone'), 'scheduled_messages', ['phone'], unique=False)
    op.create_index(op.f('ix_scheduled_messages_send_time'), 'scheduled_messages', ['send_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_messages_send_time'), table_name='scheduled_messages')
    op.drop_index(op.f('ix_scheduled_messages_phone'), table_name='scheduled_messages')
    op.drop_index(op.f('ix_scheduled_messages_is_sent'), table_name='scheduled_messages')
    op.drop_index(op.f('ix_scheduled_messages_id'), table_name='scheduled_messages')
    op.drop_table('scheduled_messages')
    # ### end Alembic commands ###
